#%RAML 1.0
title: project1
/employeedata:
  get:
    responses:
      200:
        body:
          application/json:
            example:
             [{
"name":"ranjith",
"organization":"RMSI",
"designation":"process executive",
"experience":"2.2",
"salery":"16000"
},
{
"name":"ranjith1",
"organization":"COGNIZANT",
"designation":"seniorprocess executive",
"experiance":"1.8",
"salery":"20000"
}]
        